### ISSUE TITLE
Talk about currency

### ISSUE THREAD

**Issue by steakunderscore** [rubysg/singapore#10]
It would be handy to know things like; if I need to bring local currency and if I can use cash or my credit card.

This is also related to #9

**Comment by duykhoa** [comment]
I did bring cash.
You can exchange in Singapore airport also, I think the rate is a little bit lower.

If your credit card is available in Singapore, it's awesome, cause you can pay by credit card in most of restaurant or shop.

I'm just new, may be I'm wrong. Love to hear from you!

**Comment by cykhoo** [comment]
I'd have some Singapore dollars handy if I were you. There are money changers at the airport and ATMs everywhere which will painlessly sell you Singdollars at the push of a button.

Credit cards are widely accepted here, but there are plenty of places which will only take cash. Certainly for public transport, cash is more heavily used. The best local food can be found in the older hawker centres and can't be bought with a credit card :)

Also, some retailers have a naughty habit of slapping on surcharges for credit card purchases, so, if you're shopping for say electronic goods, you might find that you get a small "discount" for paying by cash.

**Comment by tommi-lew** [comment]
- Recommend to carry some cash :dollar: 
- You might visit a handful of shops which doesn't accept credit cards.
- If you prefer to use credit card - VISA and MasterCard are commonly accepted. Many retailers still don't accept AMEX. I vaguely recall some retailers accepting Discover, but best to assume most don't.

**Comment by steakunderscore** [comment]
Thanks. There's some great answers. We should put a PR.
