### ISSUE TITLE
co-working spaces

### ISSUE THREAD

**Issue by ngpestelos** [rubysg/singapore#12]
Please add a list of co-working spaces for those who plan to work while visiting Singapore.

**Comment by cheeaun** [comment]
There's a few here https://github.com/webuildsg/lists#co-working-spaces

**Comment by ngpestelos** [comment]
thanks!

**Comment by winston** [comment]
Going to reopen the issue. Will be good to add a cross link to the link provided above. :)

**Comment by ngpestelos** [comment]
https://github.com/rubysg/singapore/pull/14

**Comment by Learnemy** [comment]
What about this? https://www.techinasia.com/hottest-coworking-spaces-southeast-asia/
