### ISSUE TITLE
Query about charging sockets.

### ISSUE THREAD

**Issue by iCHAIT** [rubysg/singapore#25]
Hello Everyone, first of all thanks for preparing such a useful list.

I am an Indian and I'll be travelling to Singapore on 16th March and will be staying for a week. I own a Macbook Air (early 2015 model) and an iPhone 6, my question is do I need to buy a universal adapter/plug for charging these devices or not?

If I need to buy one, can someone link me a reliable and good quality universal adapter from Amazon that would work for sockets in Singapore.

Looking forward to your reply :)

Thanks a lot for this list, and keep up the good work.

**Comment by Drenmi** [comment]
Hi @iCHAIT!

In Singapore we use the Type G plug. If you got your electronics in India, I assume you're on Type D.

You could try something like [this plug](http://www.amazon.com/Ceptics-Grounded-Universal-Adapter-Germany/dp/B007YKUWN4) on Amazon. (Make sure you select Type G!)

I can't attest to the quality though, so make sure you read the reviews.

Good luck! :grinning:

**Comment by iCHAIT** [comment]
Thanks a lot :)
